# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sls_checkin"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "awskrug_sls_checkin"
region = "ap-northeast-2"
disable_rollback = true
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev]
[dev.global]
[dev.global.parameters]
stack_name = "dev-sls-checkin"

[dev.deploy]
[dev.deploy.parameters]
s3_prefix = "dev-sls-checkin"
region = "ap-northeast-2"
resolve_s3 = true
disable_rollback = true
image_repositories = []
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = [
    "NowEnvironment=dev"
]

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "prod-sls-checkin"

[prod.deploy]
[prod.deploy.parameters]
s3_prefix = "prod-sls-checkin"
region = "ap-northeast-2"
resolve_s3 = true
disable_rollback = true
image_repositories = []
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = [
    "NowEnvironment=prod"
]