AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  csv-handler

Parameters:
  NowEnvironment:
    Type: String

Globals:
  Function:
    Timeout: 20
    MemorySize: 256
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  CSVBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '{{resolve:ssm:/${NowEnvironment}/csv-s3}}'

  QrBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '{{resolve:ssm:/${NowEnvironment}/qr-s3}}'

  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${NowEnvironment}-event
      AttributeDefinitions:
        - AttributeName: event_code
          AttributeType: S
      KeySchema:
        - AttributeName: event_code
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  EventCheckInTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${NowEnvironment}-event-checkin
      AttributeDefinitions:
        - AttributeName: phone
          AttributeType: S
        - AttributeName: event_code
          AttributeType: S
      KeySchema:
        - AttributeName: phone
          KeyType: HASH
        - AttributeName: event_code
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  EventRegistrationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${NowEnvironment}-event-registration
      AttributeDefinitions:
        - AttributeName: event_code
          AttributeType: S
        - AttributeName: phone
          AttributeType: S
      KeySchema:
        - AttributeName: event_code
          KeyType: HASH
        - AttributeName: phone
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  EventOrganizationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${NowEnvironment}-event-organization
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: organization_code
          AttributeType: S
      KeySchema:
        - AttributeName: organization_code
          KeyType: HASH

  BucketInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt HandlerFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt CSVBucket.Arn

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref NowEnvironment
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'https://checkin.awskr.org'"

  CommonLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: !Sub "${NowEnvironment}-common-layer"
        ContentUri: common_layer/
        RetentionPolicy: Retain
        CompatibleRuntimes:
          - python3.11
      Metadata:
        BuildMethod: makefile
        BuildArchitecture: x86_64

  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${NowEnvironment}-csv-handler"
      CodeUri: csv_handler/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - Statement:
          - Effect: Allow
            Action:
              - dsql:*
            Resource: '*'
        - S3ReadPolicy:
            BucketName: !Sub '{{resolve:ssm:/${NowEnvironment}/csv-s3}}'
      Environment:
        Variables:
          TZ: Asia/Seoul
          ENV: !Sub ${NowEnvironment}
          CLIENT_URL: !Sub '{{resolve:ssm:/${NowEnvironment}/client-url}}'
          QR_S3_BUCKET_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/qr-s3}}'
          SMTP_USERNAME: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-username}}'
          SMTP_PASSWORD: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-password}}'
          SALT: !Sub '{{resolve:ssm:/${NowEnvironment}/salt}}'
          CLUSTER_ARN: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-arn}}'
          CLUSTER_ENDPOINT: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-endpoint}}'
          DB_USER: !Sub '{{resolve:ssm:/${NowEnvironment}/db-user}}'
          DB_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/db-name}}'
          REGION: !Sub '{{resolve:ssm:/${NowEnvironment}/region}}'
      Events:
        CSVUploadEvent:
          Type: S3
          Properties:
            Bucket: !Ref CSVBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .xlsx
      Layers:
        - !Ref CommonLayer
        - "arn:aws:lambda:ap-northeast-2:770693421928:layer:Klayers-p311-pandas:22"
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${NowEnvironment}-api-handler"
      CodeUri: api_handler/
      Handler: app.lambda_handler
      Runtime: python3.11
      MemorySize: 1024
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - Statement:
          - Effect: Allow
            Action:
              - dsql:*
            Resource: '*'
      Environment:
        Variables:
          TZ: Asia/Seoul
          ENV: !Sub ${NowEnvironment}
          CLIENT_URL: !Sub '{{resolve:ssm:/${NowEnvironment}/client-url}}'
          QR_S3_BUCKET_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/qr-s3}}'
          SMTP_USERNAME: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-username}}'
          SMTP_PASSWORD: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-password}}'
          SALT: !Sub '{{resolve:ssm:/${NowEnvironment}/salt}}'
          CLUSTER_ARN: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-arn}}'
          CLUSTER_ENDPOINT: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-endpoint}}'
          DB_USER: !Sub '{{resolve:ssm:/${NowEnvironment}/db-user}}'
          DB_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/db-name}}'
          REGION: !Sub '{{resolve:ssm:/${NowEnvironment}/region}}'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /check
            Method: POST
            RestApiId: !Ref ApiGateway
        CheckinInfoEvent:
          Type: Api
          Properties:
            Path: /checkin/info
            Method: GET
            RestApiId: !Ref ApiGateway
      Layers:
        - !Ref CommonLayer

  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${NowEnvironment}-email-handler"
      CodeUri: email_handler/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - Statement:
          - Effect: Allow
            Action:
              - dsql:*
            Resource: '*'
      Environment:
        Variables:
          TZ: Asia/Seoul
          ENV: !Sub ${NowEnvironment}
          CLIENT_URL: !Sub '{{resolve:ssm:/${NowEnvironment}/client-url}}'
          QR_S3_BUCKET_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/qr-s3}}'
          SMTP_USERNAME: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-username}}'
          SMTP_PASSWORD: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-password}}'
          SALT: !Sub '{{resolve:ssm:/${NowEnvironment}/salt}}'
          CLUSTER_ARN: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-arn}}'
          CLUSTER_ENDPOINT: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-endpoint}}'
          DB_USER: !Sub '{{resolve:ssm:/${NowEnvironment}/db-user}}'
          DB_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/db-name}}'
          REGION: !Sub '{{resolve:ssm:/${NowEnvironment}/region}}'
      Layers:
        - !Ref CommonLayer
      Events:
        StreamEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt EventCheckInTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 5

  EventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${NowEnvironment}-event-handler"
      CodeUri: event_handler/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSSMReadOnlyAccess
        - Statement:
          - Effect: Allow
            Action:
              - dsql:*
            Resource: '*'
        - S3CrudPolicy:
            BucketName: !Sub '{{resolve:ssm:/${NowEnvironment}/qr-s3}}'
      Environment:
        Variables:
          TZ: Asia/Seoul
          ENV: !Sub ${NowEnvironment}
          CLIENT_URL: !Sub '{{resolve:ssm:/${NowEnvironment}/client-url}}'
          QR_S3_BUCKET_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/qr-s3}}'
          SMTP_USERNAME: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-username}}'
          SMTP_PASSWORD: !Sub '{{resolve:ssm:/${NowEnvironment}/smtp-password}}'
          SALT: !Sub '{{resolve:ssm:/${NowEnvironment}/salt}}'
          CLUSTER_ARN: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-arn}}'
          CLUSTER_ENDPOINT: !Sub '{{resolve:ssm:/${NowEnvironment}/cluster-endpoint}}'
          DB_USER: !Sub '{{resolve:ssm:/${NowEnvironment}/db-user}}'
          DB_NAME: !Sub '{{resolve:ssm:/${NowEnvironment}/db-name}}'
          REGION: !Sub '{{resolve:ssm:/${NowEnvironment}/region}}'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /event
            Method: POST
            RestApiId: !Ref ApiGateway
        EventListEvent:
          Type: Api
          Properties:
            Path: /event
            Method: GET
            RestApiId: !Ref ApiGateway
        EventUpdateEvent:
          Type: Api
          Properties:
            Path: /event
            Method: PUT
            RestApiId: !Ref ApiGateway
        EventDeleteEvent:
          Type: Api
          Properties:
            Path: /event
            Method: DELETE
            RestApiId: !Ref ApiGateway
      Layers:
        - !Ref CommonLayer
Outputs:
  CommonLayer:
    Description: CommonLayer Lambda Layer ARN
    Value: !Ref CommonLayer