name: Deploy SAM Application

on:
  push:
    branches:
      - develop
      - main
env:
  AWS_REGION: ap-northeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Set environment
        run: |
          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            echo "SAM_ENV=prod" >> $GITHUB_ENV
          else
            echo "SAM_ENV=dev" >> $GITHUB_ENV
          fi

      - name: Build SAM application
        run: |
          sam build --config-env ${{ env.SAM_ENV }}

      - name: Deploy SAM application
        run: |
          sam deploy --config-env ${{ env.SAM_ENV }} \
                     --no-confirm-changeset \
                     --no-fail-on-empty-changeset \
                     --capabilities CAPABILITY_IAM